title: Kenneth Hughes
description: Physical Oceanographer
author: Kenneth Hughes
github: https://github.com/hugke729

urls:
    - text: Publications
      url: /publications/
    - text: Photos
      url: /photos/
    - text: Presentations
      url: /presentations/
    - text: CV
      url: /docs/K%20Hughes%20CV.pdf
    - text: Research
      url: /research/
    - text: Blog
      url: https://brushingupscience.com
    - text: Data
      url: /data/

url: "https://hugke729.github.io"
baseurl: ""
markdown: kramdown
